<a href="https://colab.research.google.com/github/sahoop2002/data-science/blob/main/Numpy_tuotorial_2nd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LOAD IN NUMPY

In [1]:
import numpy as np

# THE BASICS

In [21]:
a = np.array([1,2,3],dtype ='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[5.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [5. 5. 4.]]


In [4]:
# GET DIMENSIONS
a.ndim


1

In [5]:
# get shape
b.shape

(2, 3)

In [22]:
# get type
a.dtype

dtype('int32')

In [23]:
# get size
a.itemsize


4

In [24]:
#get total size
a.nbytes

12

**# ACCESSING/CHANGING SPECIFIC ELEMENTS, ROWS,COLUMNS, ETC.**

In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
#get a specific element [r,c]
print(a[1,5])

13


In [35]:
print(a[1,-2])

13


In [36]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
# get a specific column
a[ :, 2]

array([ 3, 10])

In [40]:
# getting a little more fancy [starindex:endindex:stepsize]
print(a[0, 1:6:2])
print()
print(a[0, 1:-1:2])

[2 4 6]

[2 4 6]


In [44]:
a[1,5]=20
print(a)
print()

a[:,2] =5
print(a)
print()

a[:,2] =[1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [46]:
# 3-d example

b = np.array ([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
# get specific element (work outside in)
print(b[:,1,:])
print()
print(b[0,1,1])

[[3 4]
 [7 8]]

4


**INITIALIZING DIFFERNT TYPES OF ARRAY**

In [56]:
 # all 0s matrix
 np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
# all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [62]:
# any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [63]:
# any other number(full_like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [73]:
# random decimal numbers
np.random.rand (4,2,3) #np.random.random_sample(a.shape)


array([[[0.9878354 , 0.99360603, 0.43296473],
        [0.27418076, 0.13923709, 0.58952461]],

       [[0.1255327 , 0.10983381, 0.41831223],
        [0.94444264, 0.96877641, 0.61176055]],

       [[0.76468064, 0.4167232 , 0.42921381],
        [0.42165544, 0.91808685, 0.41302174]],

       [[0.54156494, 0.89034648, 0.85368273],
        [0.01770354, 0.17849024, 0.52507039]]])

In [78]:
# random integer values
np.random.randint(-7,7,size=(3,3))

array([[ 1,  6,  5],
       [-6, -2,  3],
       [ 5, -5, -3]])

In [80]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
# repeat an array
a1 = np.array([[1,2,3]])
r1 = np.repeat(a1,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [90]:
output = np.ones((5,5))
print(output)
print()
z = np.zeros((3,3))
z[1,1]=9
print(z)
print()
output[1:-1,1:-1]=z
print(output)
print()
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when coping arrays !!!!!

In [93]:
a = np.array([1,2,3])
b = a
print(b)
b[0]=100
print(b)
print(a)


[1 2 3]
[100   2   3]
[100   2   3]


In [95]:
a1 = np.array([1,2,3])
b1 = a1.copy()
b1[0]=100
print(b1)
print(a1)

[100   2   3]
[1 2 3]


### Mathematics

In [96]:
a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [98]:
print(a + 2)

[3 4 5 6 7]


In [99]:
print(a-2)

[-1  0  1  2  3]


In [100]:
print(a*2)


[ 2  4  6  8 10]


In [102]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [101]:
print(a%2)

[1 0 1 0 1]


In [105]:
b = np.array([1,0,1,0,1])
print(a+b)

[2 2 4 4 6]


In [106]:
print(a**2)

[ 1  4  9 16 25]


In [109]:
# take the sin cos etc.
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


###Linear Algebra

In [113]:
a = np.ones((2,3))
print(a)
print()
b = np.full((3,2),2)
print(b)
print()
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]

[[6. 6.]
 [6. 6.]]


In [115]:
# find the determinant
c = np.identity(3)
print(np.linalg.det(c))


1.0


### Statistics

In [116]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [118]:
print(np.min(stats, axis = 1))


[1 4]


In [119]:
print(np.max(stats))

6


In [120]:
print(np.sum(stats,axis=1))

[ 6 15]


### Reorganizing Arrays

In [125]:
before =  np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print()
after = before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [128]:
# vertically stacking vectores
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print()
print(np.vstack([v1,v2,v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [129]:
# horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(np.hstack([h1,h2]))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


### MISCELLANEOUS

In [ ]:
filedata = np.genfromtext('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

In [ ]:
# Boolean masking and advance indexing
filedata > 50
filedata[filedata > 50]

np.any (filedata > 50,axis = 0)
np.all (filedata > 50,axis = 0 )

[(filedata > 50) & (filedata < 100)]
[~((filedata > 50) & (filedata < 100))]


In [142]:
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]])


[2 3 9]
